{% set name = "mpl_animators" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ba5ac460bd764fde30e9b5b0714673446f0cfbb1a30d5040ade0e3434d40d1d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.7
    - numpy >=1.17.0
    - astropy >=4.2.0
    - matplotlib-base >=3.2.0

test:
  imports:
    - mpl_animators
  requires:
    - pip
    - pytest
    - pytest-mpl
  commands:
    - pip check
    - pytest --pyargs mpl_animators

about:
  home: https://sunpy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Interactive animations with matplotlib
  doc_url: https://docs.sunpy.org/projects/mpl-animators
  dev_url: https://github.com/sunpy/mpl-animators

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
