{% set name = "mpl_animators" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f82a41508cb9ed89a59b75ccb69849d9e4b25ecd2b009608b1b5b1ffa6b4ccb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17.0
    - astropy-base >=4.2.0
    - matplotlib-base >=3.2.0

test:
  imports:
    - mpl_animators
  requires:
    - pip
    - pytest
    - pytest-mpl
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --pyargs mpl_animators

about:
  home: https://sunpy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Interactive animations with matplotlib
  doc_url: https://docs.sunpy.org/projects/mpl-animators
  dev_url: https://github.com/sunpy/mpl-animators

extra:
  recipe-maintainers:
    - Cadair
    - DanRyanIrish
